### ISSUE TITLE
Order of homepage

### ISSUE THREAD

**Issue by swvanderlaan** [MillerLab-CPHG/PlaqView#14]
On the homepage of PlaqView it states 'load dataset' and 'start query'. To some it is unclear what to do. A collaborator was getting frustrated because they couldn't find the gene, but they were unaware they were loading the first dataset (Alencar) constantly. 

Suggest to have the table of datasets as a pulldown menu or to the left of the 'load dataset'-button. In either case, make it so that it is absolutely logical and clear that you need to _select_ something first before clicking the 'load dataset'-button.

**Comment by wfma** [comment]
mark as to do!

**Comment by wfma** [comment]
closing this for now. the newest release will have clear instructions. we will also attempt to disable preselection based on user feedback!
