### ISSUE TITLE
Downloads of UMAP plot

### ISSUE THREAD

**Issue by swvanderlaan** [MillerLab-CPHG/PlaqView#15]
When I hit the button for the download of the UMAP, I don't get a PNG or other image-file type, but rather `downloadumapplot.html` as a file. 

My system: 
macOS Monterey, 12.2 (21D49)
Safari 15.3 (17612.4.9.1.5)

**Comment by wfma** [comment]
sorry about that, working on it now.

**Comment by wfma** [comment]
this has been fixed in the latest release. please reopen if yall still find any trouble!
