### ISSUE TITLE
Plaqview Dataset loading not loading

### ISSUE THREAD

**Issue by salmahachim** [MillerLab-CPHG/PlaqView#17]
Dear Plaqview team, 

I am writing you regarding the platform Plaqview, upon selecting a data, I have attempted this with both Datasets “Alsaigh_2020” (human) and “Alencar_2020” (human) and  set and clicking on “load Dataset”, it continuously keeps loading (I am at over an hour currently) and the “start Exploring” button never appears. Could you please help me with this?  

Kind regards,
Salma Hachim

**Comment by wfma** [comment]
Hi, apologies for the delay. The data are simply too large for your instance I think, we are working on a down-sampled dataset soon.
